#!/bin/bash
# Get user info
read -p 'Name: ' name
read -p 'program name: ' prog
read -p 'Enrolment number: ' enrol
echo
echo  $name $prog $enrol is the entered details #!/bin/bash
N=4
i=1
sum=0
mul=1
echo "Enter Numbers"
while [ $i -le $N ]
do
  read num               
  sum=$((sum + num))     
  mul=$((mul * num))
  i=$((i + 1))
done
avg=$(echo $sum / $N | bc -l)
printf "Average $avg Sum $sum Product $mul"
